### ISSUE TITLE
Error with Mandarin Chinese

### ISSUE THREAD

**Issue by ghost** [thiswillbeyourgithub/AnnA_Anki_neuronal_Appendix#15]
I get this error when trying to run the script with Chinese. Works perfectly with other languages.
First I thought it was due to the fact that there aren't many due cards, but I tried yesterday with more than 200 cards and it dropped the same error.

```
python3.9 autorun.py                                                          ✔ 
    _                   _    
   / \   _ __  _ __    / \   
  / _ \ | '_ \| '_ \  / _ \  
 / ___ \| | | | | | |/ ___ \ 
/_/   \_\_| |_|_| |_/_/   \_\
                             

(Anki neuronal Appendix)


Couldn't find this deck.
Enter the name of the deck:
>Mandarin
Selected deck: Mandarin

Task : created filtered deck containing review cards
Getting due card list...
 >  '"deck:Mandarin" is:due is:review -is:learn -is:suspended -is:buried -is:new -rated:1'
Found 15 reviews...

Getting cards that where rated in the last 3 days...
 >  '"deck:Mandarin" rated:3 -is:suspended -is:buried'
Found 49 cards...

Asking Anki for information about 64 cards...
(Large number of cards to retrieve: creating 10 threads of size 15)

Done threads: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 5/5 [00:02<00:00,  2.00thread/s]
Got all infos in 2 seconds.

Combining relevant fields: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████| 64/64 [00:00<00:00, 961.35 card/s]
Formating text: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████| 64/64 [00:00<00:00, 911.42 card/s]


Printing 2 random samples of your formated text, to help adjust formating issues:
 * 1631661855764 : 开口: 開口 word OM ts list
 * 1631661854970 : 上去 word fresh ts list


Looking for acronyms that perhaps should be in 'acronym_file'...
No acronym found in those cards.
Vectorizing text using TFIDF: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████| 64/64 [00:00<00:00, 6736.32it/s]

Reducing dimensions to 100 using SVD... Traceback (most recent call last):
  File "/home/yaoberh/.local/share/Anki2/addons21/AnnA_Anki_neuronal_Appendix/autorun.py", line 16, in <module>
    AnnA(deckname="Some_Deck",
  File "/home/yaoberh/.local/share/Anki2/addons21/AnnA_Anki_neuronal_Appendix/AnnA.py", line 321, in __init__
    self._compute_card_vectors()
  File "/home/yaoberh/.local/share/Anki2/addons21/AnnA_Anki_neuronal_Appendix/AnnA.py", line 853, in _compute_card_vectors
    t_red = svd.fit_transform(t_vec)
  File "/home/yaoberh/.local/lib/python3.9/site-packages/sklearn/decomposition/_truncated_svd.py", line 207, in fit_transform
    raise ValueError(
ValueError: n_components must be < n_features; got 76 >= 76

```

**Comment by thiswillbeyourgithub** [comment]
Hi!

Thanks for the interest, it makes me happy :)

This is indeed a bug, I thought I already fixed it in the passed but was missing a +1 offset.

Here's the fix : 7a231a5135992e9b7210438366c9952801f4abb9


Thanks a lot :)
