### ISSUE TITLE
[Anki 23.10 beta 6] No module named 'PyQt5'

### ISSUE THREAD

**Issue by khonkhortisan** [thiswillbeyourgithub/AnnA_Anki_neuronal_Appendix#24]
> The Qt5 compatibility code is now off by default, which may break some add-ons that haven't been updated to support Qt6 in the last 2 years. If you find any have broken, please report the issues to the add-on author, and start Anki after setting the env var ENABLE_QT5_COMPAT to 1 to temporarily restore the compatibility code.

```py
Error
Un complemento que has instalado ha fallado al cargarse. Si los problemas persisten, por favor ve a Herramientas> Menú de complementos o deshabilita este complemento.

Mientras cargando '⁨AnnA Companion Anki neuronal Appendix - do LESS reviews with MORE retention⁩':
⁨Traceback (most recent call last):
  File "aqt.addons", line 239, in loadAddons
  File "C:\Users\Khonkhortisan\AppData\Roaming\Anki2\addons21\447942356\__init__.py", line 19, in <module>
    from PyQt5 import QtCore
ModuleNotFoundError: No module named 'PyQt5'
```
447942356\\_\_init\_\_.py
```py
#from PyQt5 import QtCore
#from PyQt5.QtCore import QTimer
#from PyQt5.QtWidgets import QMessageBox
try:
    from PyQt6 import QtCore
    from PyQt6.QtCore import QTimer
    from PyQt6.QtWidgets import QMessageBox
except ImportError:
    from PyQt5 import QtCore
    from PyQt5.QtCore import QTimer
    from PyQt5.QtWidgets import QMessageBox
```

**Comment by thiswillbeyourgithub** [comment]
Thanks. I pushed it but won't have time to merge the main and dev branch for a while and won't update the addon before that.
