### ISSUE TITLE
Doesn't create logs.txt, and therefore crashes

### ISSUE THREAD

**Issue by aleksejrs** [thiswillbeyourgithub/AnnA_Anki_neuronal_Appendix#6]
If `logs.txt` doesn't exist when I start the program, it fails with

```
$ python3 ./autorun.py 
Traceback (most recent call last):
  File "/mnt/addons/AnnA_Anki_neuronal_Appendix/./autorun.py", line 7, in <module>
    from AnnA import *
  File "/mnt/addons/AnnA_Anki_neuronal_Appendix/AnnA.py", line 41, in <module>
    Path("logs.txt").read_text().split("\n")[-5000:]))
  File "/usr/lib/python3.9/pathlib.py", line 1255, in read_text
    with self.open(mode='r', encoding=encoding, errors=errors) as f:
  File "/usr/lib/python3.9/pathlib.py", line 1241, in open
    return io.open(self, mode, buffering, encoding, errors, newline,
  File "/usr/lib/python3.9/pathlib.py", line 1109, in _opener
    return self._accessor.open(self, flags, mode)
FileNotFoundError: [Errno 2] No such file or directory: 'logs.txt'
```

commit 5d74d65aef30fc040d7e39d79e108471b77aee7d

**Comment by thiswillbeyourgithub** [comment]
Fixed in 0591a7348a74dca053aacbbdb1456f39ed3f7e58

Thanks!
