### ISSUE TITLE
tqdm.std.TqdmKeyError: "Unknown argument(s): {'delay': 2}"

### ISSUE THREAD

**Issue by aleksejrs** [thiswillbeyourgithub/AnnA_Anki_neuronal_Appendix#7]
```
Traceback (most recent call last):
  File "/mnt/addons/AnnA_Anki_neuronal_Appendix/./autorun.py", line 15, in <module>
    AnnA(deckname="/::s",
  File "/mnt/addons/AnnA_Anki_neuronal_Appendix/AnnA.py", line 307, in __init__
    self._init_dataFrame()
  File "/mnt/addons/AnnA_Anki_neuronal_Appendix/AnnA.py", line 505, in _init_dataFrame
    self._getCardsInfo(
  File "/mnt/addons/AnnA_Anki_neuronal_Appendix/AnnA.py", line 386, in _getCardsInfo
    with tqdm(total=target_thread_n,
  File "/home/fc/.local/lib/python3.9/site-packages/tqdm/std.py", line 1002, in __init__
    raise (
tqdm.std.TqdmKeyError: "Unknown argument(s): {'delay': 2}"
```

```
$ pip show tqdm
Name: tqdm
Version: 4.55.1
Summary: Fast, Extensible Progress Meter
Home-page: https://github.com/tqdm/tqdm
Author: None
Author-email: None
License: MPLv2.0, MIT Licences
Location: /home/fc/.local/lib/python3.9/site-packages
Requires: 
Required-by: nltk
```

**Comment by thiswillbeyourgithub** [comment]
I'm currently on tqdm version 4.62.3

I pushed a new line to requirements to mention that : a15520ef39eb8198bf4ceb86e3ead2d39b57354e

Thanks!

**Comment by aleksejrs** [comment]
You didn't remove the existing line:

```
$ pip install -r requirements.txt
WARNING: Keyring is skipped due to an exception: Failed to unlock the keyring!
Collecting tqdm==4.62.3
  Downloading tqdm-4.62.3-py2.py3-none-any.whl (76 kB)
     |████████████████████████████████| 76 kB 1.2 MB/s 
Requirement already satisfied: pyfiglet==0.8.post1 in /home/fc/.local/lib/python3.9/site-packages (from -r requirements.txt (line 2)) (0.8.post1)
Requirement already satisfied: prompt_toolkit==3.0.14 in /usr/lib/python3/dist-packages (from -r requirements.txt (line 3)) (3.0.14)
Requirement already satisfied: python_Levenshtein==0.12.2 in /home/fc/.local/lib/python3.9/site-packages (from -r requirements.txt (line 4)) (0.12.2)
Requirement already satisfied: pandas==1.2.3 in /home/fc/.local/lib/python3.9/site-packages (from -r requirements.txt (line 6)) (1.2.3)
Requirement already satisfied: numpy==1.19.4 in /home/fc/.local/lib/python3.9/site-packages (from -r requirements.txt (line 8)) (1.19.4)
Requirement already satisfied: sklearn==0.0 in /home/fc/.local/lib/python3.9/site-packages (from -r requirements.txt (line 9)) (0.0)
ERROR: Cannot install tqdm==4.55.1 and tqdm==4.62.3 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested tqdm==4.62.3
    The user requested tqdm==4.55.1

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies
```

**Comment by thiswillbeyourgithub** [comment]
Sorry, I'm in a rush

Fixed!

Thanks!
